### ISSUE TITLE
Make the sourceMappingURL absolute url

### ISSUE THREAD

**Issue by wildskyf** [leifcr/uglifier_with_source_maps#2]
as title, Firefox requires that url to be avsolute url, or it will show this warning:

```
Source Map Error: request failed with status 404 Source Url: https://example.com/assets/script.min.js
Source Map Url: /assets/path/to/script.map
```

**Comment by wildskyf** [comment]
According to spec, absolute is not required.

**Comment by leifcr** [comment]
I suggest using latest sprockets (4.0 beta) instead, as it supports source maps.

If you work with more complicated js, and use babel or yarn or similar for compiling js, use that to compile sourcemaps instead, as it's better.
